name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.4.1
  intl: ^0.20.1

dev_dependencies:
  drift_dev: ^2.28.3
  build_runner: ^2.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
